apiVersion: apps/v1
# ở đây phiên bản cũ hơn của kubernetes có dạng extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-taile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-taile
  template:
    metadata:
      labels:
        app: nginx-taile
    spec:
      containers:
      - name: nginx-taile
        image: nginx
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-taile
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: nginx-taile
  type: ClusterIP
